### PR TITLE
Update cabal information on hackage. Closes #107.

### LINKED ISSUE #107: Fix hackage / cabal metadata
See http://hackage.haskell.org/package/graphql-api

- Author shouldn't be blank
- Maintainer should include @jml and @teh 
- Stability should be "unstable" (or equivalent)

### PR DESCRIPTION
**Pull request by sunwukonga**
Also took the liberty to change the synopsis field. It lacked specificity.

Edited `package.yaml` then called `hpack`. Apologies for the meaningless churn in `graphql-api.cabal`.

### CODE REVIEW

**Comment by jml** [comment]
Thanks. 

I guess we'll have to cut a release for this to show up on hackage?

**Comment by sunwukonga** [comment]
Yes, I imagine that's how it works. You'll have to introduce a feature/fix a bug that is worthy of a bump :D

**Comment by jml** [comment]
Thanks. I've heard tell of legends of hackage maintainers silently fixing
things, and wondered whether this was one such time.

**Comment by sunwukonga** [comment]
You can edit package information directly on hackage: https://hackage.haskell.org/package/graphql-api/maintain

**Pull request merged**
