### PR TITLE
Add upper bound to protolude.

### PR DESCRIPTION
**Pull request by teh**
@tibastral can you give this branch a spin?

### CODE REVIEW

**Comment by tibastral** [comment]
I have that response :

Resolving dependencies...
cabal: Could not resolve dependencies:
trying: graphql-api-0.1.2 (user goal)
trying: base-4.10.0.0/installed-4.1... (dependency of graphql-api-0.1.2)
next goal: protolude (dependency of graphql-api-0.1.2)
rejecting: protolude-0.2/installed-LXt..., protolude-0.2 (conflict:
graphql-api => protolude<0.2)
rejecting: protolude-0.1.10, protolude-0.1.9, protolude-0.1.8,
protolude-0.1.7, protolude-0.1.6, protolude-0.1.5, protolude-0.1.4,
protolude-0.1.3, protolude-0.1.2, protolude-0.1.1 (conflict:
base==4.10.0.0/installed-4.1..., protolude => base>=4.6 && <4.10)
rejecting: protolude-0.1.0 (conflict: base==4.10.0.0/installed-4.1...,
protolude => base<0)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, graphql-api, protolude

**Comment by jml** [comment]
What ghc are you using?

**Comment by tibastral** [comment]
Installed through https://www.haskell.org/platform/mac.html

**Comment by jml** [comment]
OK. That's GHC 8.2. I suspect that changes to `base` have compelled changes to `protolude`, and that we need to update `graphql-api` to support both versions.

**Comment by teh** [comment]
I think we can close this with https://github.com/jml/graphql-api/pull/123 merged. I will roll a new release in the next few weeks.

**Pull request closed without merging**
